{
 "title": "Docker - container summary (Prometheus)",
 "description": "Container state and resource usage as collected from prometheus-net/docker_exporter",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instances",
    "label": "Instances",
    "query": "label_values(docker_container_running_state, instance)"
   },
   {
    "name": "containers",
    "label": "Containers",
    "query": "label_values(docker_container_running_state{instance =~ \"$instances\"}, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU %",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(docker_container_cpu_used_total{instance =~ \"$instances\", name =~ \"$containers\"}[1m]) / increase(docker_container_cpu_capacity_total[1m])",
     "legendFormat": "{{instance}} / {{name}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "docker_container_memory_used_bytes{instance =~ \"$instances\", name=~ \"$containers\"}",
     "legendFormat": "{{instance}} / {{name}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 21, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "time() - docker_container_start_time_seconds{instance =~ \"$instances\", name =~ \"$containers\"}"
    },
    {
     "expr": "sum(docker_container_running_state{instance =~ \"$instances\", name =~ \"$containers\"}) without (__name__)"
    },
    {
     "expr": "sum(increase(docker_container_restart_count{instance =~ \"$instances\", name =~ \"$containers\"}[$__range])) without (__name__)"
    }
   ]
  },
  {
   "title": "Network I/O (+transmit, -receive)",
   "type": "graph",
   "description": "Receive displayed as negative for easy differentiation on single panel",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(docker_container_network_in_bytes{instance =~ \"$instances\", name =~ \"$containers\"}[1m]) * -8",
     "legendFormat": "{{instance}} / {{name}} receive"
    },
    {
     "expr": "rate(docker_container_network_out_bytes{instance =~ \"$instances\", name =~ \"$containers\"}[1m]) * 8",
     "legendFormat": "{{instance}} / {{name}} transmit"
    },
    { "expr": "vector(0)", "legendFormat": "Zero point reference" }
   ]
  },
  {
   "title": "Disk I/O (+write, -read)",
   "type": "graph",
   "description": "Read displayed as negative for easy differentiation on single panel",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "-rate(docker_container_disk_read_bytes{instance =~ \"$instances\", name =~ \"$containers\"}[1m])",
     "legendFormat": "{{instance}} / {{name}} read"
    },
    {
     "expr": "rate(docker_container_disk_write_bytes{instance =~ \"$instances\", name =~ \"$containers\"}[1m])",
     "legendFormat": "{{instance}} / {{name}} write"
    },
    { "expr": "vector(0)", "legendFormat": "Zero point reference" }
   ]
  }
 ]
}