{
 "title": "Prometheus Nomad",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "nomad_nomad_job_summary_running",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "nomad_nomad_job_summary_running",
     "prometheusLink": "http://localhost:9090/graph#%5B%7B%22expr%22%3A%22nomad_nomad_job_summary_running%22%2C%22range_input%22%3A%22301s%22%2C%22end_input%22%3A%222020-1-30%205%3A47%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Client Allocations Running",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "nomad_client_allocations_running",
     "prometheusLink": "http://localhost:9090/graph#%5B%7B%22expr%22%3A%22nomad_client_allocations_running%22%2C%22range_input%22%3A%22301s%22%2C%22end_input%22%3A%222020-1-30%205%3A43%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Client Allocations Blocked",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "nomad_client_allocations_blocked",
     "prometheusLink": "http://localhost:9090/graph#%5B%7B%22expr%22%3A%22nomad_client_allocations_blocked%22%2C%22range_input%22%3A%22300s%22%2C%22end_input%22%3A%222020-1-30%205%3A43%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  { "title": "Runtime Total GS Pauses", "type": "heatmap", "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 } },
  {
   "title": "Runtime Alloc Bytes (Linux)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "nomad_runtime_alloc_bytes",
     "prometheusLink": "http://localhost:9090/graph#%5B%7B%22expr%22%3A%22nomad_runtime_alloc_bytes%22%2C%22range_input%22%3A%22300s%22%2C%22end_input%22%3A%222020-1-30%205%3A44%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "nomad_client_uptime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "nomad_client_uptime",
     "prometheusLink": "http://localhost:9090/graph#%5B%7B%22expr%22%3A%22nomad_client_uptime%22%2C%22range_input%22%3A%22300s%22%2C%22end_input%22%3A%222020-1-30%205%3A50%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  }
 ]
}